#!/bin/bash
#LogicalDoc-Backup
#START BACKUP
TIME=`date +%b-%d-%y`
FILENAMEDOC=docs.tar.gz
FILENAMEINDEX=index.tar.gz
FILENAME=logicaldoc-$TIME.tar.gz
SRCDIR=/opt/data
SRCDIRDOC=$SRCDIR/docs
SRCDIRINDEX=$SRCDIR/index
DESDIR=/opt/backup
tar -cpzf $DESDIR/$FILENAMEDOC $SRCDIRDOC
tar -cpzf $DESDIR/$FILENAMEINDEX $SRCDIRINDEX
tar -cpzf $DESDIR/$FILENAME $DESDIR/$FILENAMEDOC $DESDIR/$FILENAMEINDEX

rm $DESDIR/$FILENAMEDOC
rm $DESDIR/$FILENAMEINDEX

# delete files, older than 10 days (https://stackoverflow.com/questions/13489398/delete-files-older-than-10-days-using-shell-script-in-unix)
find $DESDIR/*.tar.gz -mtime +10 -type f -delete

#END BACKUP

